# Generated by Django 4.2.1 on 2023-06-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='medications',
            new_name='medication',
        ),
    ]
