# Generated by Django 4.2.1 on 2023-06-06 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_medications_visit_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_health', models.TextField()),
                ('sickness_history', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('medication_list', models.TextField()),
                ('medical_examination', models.TextField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.doctor')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.student')),
            ],
        ),
    ]
