# Generated by Django 4.2.1 on 2023-06-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_doctor_medication_prescription_visit_usemedication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='useMedication',
        ),
        migrations.AddField(
            model_name='prescription',
            name='useMedications',
            field=models.ManyToManyField(blank=True, to='api.usemedication'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
