# Generated by Django 4.1.7 on 2023-06-07 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_visit_is_active_documentation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("date_of_birth", models.DateField()),
                ("pesel", models.CharField(max_length=11, unique=True)),
                ("phone_number", models.CharField(max_length=9, unique=True)),
                ("address", models.CharField(max_length=95)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
