# Generated by Django 4.2.1 on 2023-06-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_prescription_usemedication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usemedication',
            name='date_of_use',
            field=models.DateField(null=True),
        ),
    ]
