# Generated by Django 4.2.1 on 2023-06-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usemedication_date_of_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usemedication',
            name='date_of_use',
            field=models.DateField(blank=True, null=True),
        ),
    ]
